name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
  
      - name: run tests
        run: go test ./... -cover

      - name: install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: perform gosec
        run: gosec ./...

  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: format test
        run: test -z $(go fmt ./...)

      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: perform staticcheck
        run: ~/go/bin/staticcheck ./...